import '@/styles/globals.css';
import type { Metadata } from 'next';
import { Palanquin_Dark } from 'next/font/google';

import Navbar from '@/components/Navbar';
import { Suspense } from 'react';

const palanquinDark = Palanquin_Dark({
    weight: '400',
    subsets: ['latin']
});

export const metadata: Metadata = {
    title: 'Valopedia',
    description: 'Generated by create next app'
};

export default function RootLayout({
    children
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={palanquinDark.className}>
                <Navbar />

                <main>{children}</main>
            </body>
        </html>
    );
}
